server:
  port: 8088
welcome:
  message: "==YOU ARE USING DEVELOPMENT ENVIRONMENT=="

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop